[package]
name = "tmexclude"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "tmexclude"
path = "./src/main.rs"

[lib]
name = "tmexclude_lib"
path = "./src/lib.rs"

[dependencies]
figment = { version = "0.10", features = ["toml", "yaml"] }
futures = "0.3"
itertools = "0.10"
log = "0.4"
notify = "5.0.0-pre.13"
parking_lot = "0.11"
pretty_env_logger = "0.4"
serde = { version = "1.0", features = ["derive"] }
thiserror = "1.0"
tokio = { version = "1.14", features = ["fs", "macros", "parking_lot", "process", "rt", "rt-multi-thread", "sync"] }
tokio-stream = "0.1"

[dev-dependencies]
maplit = "1.0"
