mode: add-only
interval:
  watch: 10s
directories:
  - path: ~/
    rules:
      - rust
      - nodejs
      - python
      - pnpm
skips:
  - ~/Library
  - ~/Pictures
  - ~/.vscode
  - ~/.npm
  - ~/Dropbox
  - ~/.dropbox
  - ~/.Trash
rules:
  rust:
    excludes:
      - target
    if-exists:
      - Cargo.toml
  nodejs:
    excludes:
      - node_modules
    if-exists:
      - package.json
  pnpm:
    excludes:
      - .pnpm-store
  python:
    excludes:
      - build
      - dist
      - venv
      - .venv
    if-exists:
      - requirements.txt
      - setup.py